### ISSUE TITLE
Drinking wine doesnt add to hunger

### ISSUE THREAD

**Issue by runelynx** [TheBusyBiscuit/ExoticGarden#10]
Took my hunger down to empty and tried drinking Wine in exotic garden 1.6.2, latest slimefun and cscorelib...   it drinks the wine OK but 0 hunger is given.

**Comment by lew69** [comment]
Hi , we got the same problem on our server .

**Comment by aycgit** [comment]
i know this is old but does the lime smoothy still work? the wine seems to be properly registered [here](https://github.com/TheBusyBiscuit/ExoticGarden/blob/976eccf33c1eb94ee59b9411a420c5f730dfc80b/src/me/mrCookieSlime/ExoticGarden/ExoticGarden.java#L224) The only possible problem i could find was the fact that it is giving saturation amplified with 0 for 10 seconds and not what i think it should be the other way around. (forgive me if im from, spigot coding was a long time ago)

**Comment by lew69** [comment]
hi , i tried the lime smoothie and it doesn"t give hunger .

**Comment by Poslovitch** [comment]
Confirmed as bug. This only gives food when used in a Cooler.

**Comment by SoSeDiK** [comment]
It was fixed in Slimefun and so is for ExoticGarden.

**Comment by Wqrld** [comment]
> It was fixed in Slimefun and so is for ExoticGarden.

bit late but always great :)
