### ISSUE TITLE
Kithcen

### ISSUE THREAD

**Issue by iliafas** [TheBusyBiscuit/ExoticGarden#101]
## Description (Required)
Hi,I have a problem with Exotic Garden's kitchen, Its working with empty dispenser (I mean It says recipe not found when nothing in it) But when ever I put required items in dispenser, nothing happens when i right click the Iron trapdoor
My slimefun version: Development #255 and ExoticGarden #24 (And also I have SlimefunOrechunks Developer #3)
## Steps to reproduce the Issue (Required)
Kitchen Dident work when i tap irontrap dore
## Expected behavior (Required)
cook some dirnks or foods
## Server Log / Error Report
dont have any log report

## Environment (Required)
Slimefun4 - RC 4 (git ec409).jar

 - Minecraft Version:1.14
 - CS-CoreLib Version: 1.6.1
 - Slimefun Version: Slimefun4 - RC 4 (git ec409).jar
 - ExoticGarden Version: dev 24

**Comment by TheBusyBiscuit** [comment]
Update CS-CoreLib and update Slimefun.
And attach a server log via pastebin...

**Comment by iliafas** [comment]
Didnt Work https://pastebin.com/qz5HYyU0

**Comment by TheBusyBiscuit** [comment]
You lied about your versions.
You are using an old version of ExoticGarden...
Update it.

**Comment by threlief** [comment]
hey i got the version 25 exotic garden and got this same problem is there going to be another update?

**Comment by threlief** [comment]
@TheBusyBiscuit  sry i hope this isnt considerd spamming cause they 20 min apart
 but is there going to be a update for exotic garden soon cause my kitchen and trees arent working as well
