### ISSUE TITLE
Entities in the same chunk as Exotic Plants turn invisible.

### ISSUE THREAD

**Issue by Deathinflames** [TheBusyBiscuit/ExoticGarden#11]
We've been noticing that entities tend to disappear when they're in a chunk with the Exotic Gardens plants. They're all still there, just can't be seen. Items, mobs (Both passive and hostile), and even players, disappear when in the same chunk as an Exotic Garden plant. 

There are no errors reported in the server logs.

Server: CraftBukkit git-Spigot-d276ab1-1f6c04c (MC: 1.11.2)

> sf versions
> [10:20:01 INFO]: CraftBukkit v1_11_R1
> [10:20:01 INFO]: CS-CoreLib v1.5.14
> [10:20:01 INFO]: Slimefun v4.1.5
> [10:20:01 INFO]: Installed Addons:
> [10:20:01 INFO]:  ExoticGarden v1.6.2

**Comment by TheBusyBiscuit** [comment]
That has nothing do with plants. Minecraft render issues with heads/entities, you should report this to Mojang if it does happen on your server.
