### ISSUE TITLE
Trees not growing / error in log

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/ExoticGarden#111]
## Description (Required)
Bushes working fine but all trees grow as oak trees.  When they do, this message appears in the log:

## Environment (Required)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - ExoticGarden Version:

**Comment by mrcoffee1026** [comment]
huh ctrl+enter must submit a ticket here, i was trying to ctrl+vf

**Comment by R4z0rX** [comment]
I have the same issue with Paper 1.14.4 build #243 (lastest).
Why is this bug report closed?

**Comment by mrcoffee1026** [comment]
i think he maybe closed this as I accidentally submitted instead of putting "enter" when just entering the ticket initially... so it was no where near complete, but probably left it closed since it's technically a duplicate of #104, not at all the same behavior... but I guess the same error.  That one is closed as he keeps thinking he's fixed it.

**Comment by R4z0rX** [comment]
Yeah, I just found it, and yes it's closed too. I don't understand why. If it's fixed, he should point us to the updated/fixed build.

**Comment by mrcoffee1026** [comment]
he THOUGHT it was fixed, it still isn't but don't open a new ticket about it.

**Comment by R4z0rX** [comment]
Well, I just updated to the latest builds of CS-CoreLib (83), SlimeFun4 (438) and ExoticGarden (31) and now the trees are generating fine in my test server (PaperMC 1.14.4 build 243). :)

**Comment by mrcoffee1026** [comment]
well they'll stop when you get to 1.15.2

**Comment by WalshyDev** [comment]
Fixed in the latest build!
