### ISSUE TITLE
startup errors in 1.14.4

### ISSUE THREAD

**Issue by siamneko** [TheBusyBiscuit/ExoticGarden#112]
## Description (Required)
Add-on doesn't start with error at startup
## Steps to reproduce the Issue (Required)
Start server in 1.14.4 with active ExoticGarden in the world.
## Expected behavior (Required)
The add-on works without these errors.
## Server Log / Error Report
https://pastebin.com/0m9u6nzt
## Environment (Required)
 - Minecraft Version:Paper v1_14_R1
 - CS-CoreLib Version:vDEV - 83 (git 8081bb4f)
 - Slimefun Version:vDEV - 436 (git a44c6671)
 - ExoticGarden Version:vDEV - 31 (git 7515d3ef)

**Comment by WalshyDev** [comment]
Fixed in the latest build!
