### ISSUE TITLE
problem?

### ISSUE THREAD

**Issue by PLPLUGIN** [TheBusyBiscuit/ExoticGarden#128]
Idk what am I doing wrong, I have paper 1.15.2 server and I installed slimefun, exotic garden and this library and it shows in /plugins "exotic garden" but it doesn't work

**Comment by PLPLUGIN** [comment]
-_-

**Comment by PLPLUGIN** [comment]
you didn't even help me -_-

**Comment by TheBusyBiscuit** [comment]
Follow the template.
