### ISSUE TITLE
Exotic Garden problems with head-items...

### ISSUE THREAD

**Issue by roracle** [TheBusyBiscuit/ExoticGarden#13]
When right-clicking anything (such as a chest or a EG bush) with (for example) a raspberry, the raspberry disappears forever.
I have not tried this with basic SlimeFun items, but I can later on to find out if it's a SF problem or Exotic Garden.
If others have noticed this issue, or you would like more information, please respond!

**Comment by TheBusyBiscuit** [comment]
Well, you ate it...
