### ISSUE TITLE
Exotic garden items get duplicated

### ISSUE THREAD

**Issue by yumjunstar** [TheBusyBiscuit/ExoticGarden#138]
## Description (Required)
-It happens in Slimefun 4, in the block that is fence or a stone step.
It happens with items in Exotic Gardens, 
only for one-blocked plants such as Strawberry or Grape.
I can define it, A sapling Duplicating Bug.

## Steps to reproduce the Issue (Required)
-First, you need a step (or fence) block right next to the chunk surface, and you need a floor.
Second, you need to place one-blocked plant in the block. But make it next to the block, not up or down.
Third, If you succeed on placing it, you need to harvest it. 
Fourth, then there will be a plant and its Sapling.
Fifth, Do it several times, and then you will find you holding lots of Sapling.

## Expected behavior (Required)
-You can duplicate onions or garlics, so it will be a lot easy to make foods like Hamburger, 
or maybe some juices.
Also, you can duplicate oak seedlings by doing it double, 
so some servers balance can be crashed.

## Server Log / Error Report
-X

## Environment (Required)
![image](https://user-images.githubusercontent.com/24960675/82121863-27cb1f80-97cb-11ea-86f8-677eba52de7f.png)

**Comment by TheBusyBiscuit** [comment]
I really have no idea on how to reproduce this.
Can you make a video?

**Comment by ItsSynchro** [comment]
Hello, I went ahead and created a video displaying the duplication glitch. 
 https://youtu.be/-MpzW2jloOY
