### ISSUE TITLE
When the map is very large, ExoticGarden often stops the server from responding.

### ISSUE THREAD

**Issue by XXY218** [TheBusyBiscuit/ExoticGarden#139]
## Description (Required)
My server map data exceeds 200GB,when the map is very large, ExoticGarden often stops the server from responding.

## Steps to reproduce the Issue (Required)
![20200519190531](https://user-images.githubusercontent.com/46647646/82320964-b7a8dd80-9a06-11ea-871b-a709c0e7ed84.png)
![20200519192747](https://user-images.githubusercontent.com/46647646/82321055-d909c980-9a06-11ea-9689-e49bea8a3cc2.png)
Just keep going, and then the server is likely to stop responding

## Expected behavior (Required)
I hope that this situation can be improved, or that less frequently used data can be automatically cleaned up.

## Server Log / Error Report
https://pastebin.com/QDj9C4Zy
https://pastebin.com/iSGgKFWV

## Environment (Required)
![20200519192847](https://user-images.githubusercontent.com/46647646/82321160-fdfe3c80-9a06-11ea-9974-80dbeca52363.png)

**Comment by AustinCZ** [comment]
I can confirm this on multiple servers we are hosting. It is even more extreme if you combine it with WorldBorder fill. It is then generating chunks outside the set border with .mca files with seemingly random coordinates like r.434948.148122.mca, r.-651.6095.mca and so on... And it will fill the drive like 1 GB per/5 minutes...
