### ISSUE TITLE
Fruits heads bug

### ISSUE THREAD

**Issue by Fabrikrik** [TheBusyBiscuit/ExoticGarden#146]
## Description (Required)
Fruits heads bug

## Steps to reproduce the Issue (Required)
Hello, I've got a problem with the fruits heads, when i took them, i can't put them on the ground.
Is it a bug or it's normal ? 
Thank's by advance
 - Minecraft Version: 1.15.2
 - CS-CoreLib Version: last
 - Slimefun Version: last
 - ExoticGarden Version: last

**Comment by TheBusyBiscuit** [comment]
That's normal and don't abuse the bug tracker for this, we have a discord server...
Also "last" is not a valid version. Future issues in this manner will be deleted without warning, they are not helpful at all, stick to the template.
