### ISSUE TITLE
Error on starting // plugin disabled

### ISSUE THREAD

**Issue by Loonyy** [TheBusyBiscuit/ExoticGarden#154]
## Description (Required)
Error on starting, plugin disabled

## Server Log / Error Report
https://pastebin.com/7cw4JDcz

## Environment (Required)
13.07 23:03:00 [Server] INFO Paper v1_15_R1
13.07 23:03:00 [Server] INFO CS-CoreLib vDEV - 79 (git ec5b4c24)
13.07 23:03:00 [Server] INFO Slimefun vDEV - 566 (git cb7cc440)
13.07 23:03:00 [Server] INFO Backwards compatiblity enabled!
13.07 23:03:00 [Server] INFO Installed Addons (2)
13.07 23:03:00 [Server] INFO ExtraGear vDEV - 10 (git 892256da)
13.07 23:03:00 [Server] INFO ExoticGarden vDEV - 55 (git cce4c0f4)

 - Minecraft Version:
Minecraft 1.15.2 (Paper)
All other versions are included above

Not sure if those versions of SlimeFun and ExoticGarden aren't compatible. I'm just using the latest of everything. I tried to use the version of SF & CS-Core-Lib that's required on the ExoticGarden download page but I ran into the same issue.

**Comment by SoSeDiK** [comment]
Update your Slimefun. There's build 584 already.
