### ISSUE TITLE
Android disappeared strangely

### ISSUE THREAD

**Issue by XXY233** [TheBusyBiscuit/ExoticGarden#163]
## :round_pushpin: Description (REQUIRED)

Operate Android normally, and after a while, Android disappears by itself.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

https://youtu.be/pxtPzhwvPDs

## :bulb: Expected behavior (REQUIRED)

Android will not disappear and work normally.

## :scroll: Server Log

https://pastebin.com/FAFtFfHC

## :open_file_folder: /error-reports/ Folder

https://pastebin.com/yybk69FF

## :compass: Environment (REQUIRED)

![20201008104714](https://user-images.githubusercontent.com/46647646/95409167-a891e000-0953-11eb-9852-39b862bd1ba5.jpg)

**Comment by dissemin8** [comment]
I also have this issue. Advanced Farming Android disappears a short time after starting. First occured with Slimefun vDev #700

**Comment by reapthus** [comment]
> ## 📍 Description (REQUIRED)
> Operate Android normally, and after a while, Android disappears by itself.
> 
> ## 📑 Steps to reproduce the Issue (REQUIRED)
> https://youtu.be/pxtPzhwvPDs
> https://youtu.be/v6QsbuS46ZA

> ## 💡 Expected behavior (REQUIRED)
> Android will not disappear and work normally.
> 
> ## 📜 Server Log
> https://pastebin.com/FAFtFfHC
> https://pastebin.com/zLSZDhwT
> 
> ## 📂 /error-reports/ Folder
> https://pastebin.com/yybk69FF
> https://pastebin.com/fXVC1WJi
>
> ## 🧭 Environment (REQUIRED)
> ![20201008104714](https://user-images.githubusercontent.com/46647646/95409167-a891e000-0953-11eb-9852-39b862bd1ba5.jpg)
>![image](https://user-images.githubusercontent.com/66781302/95751302-d12c1980-0c74-11eb-9a40-11e656f5277d.png)
