### ISSUE TITLE
Error in console upon breaking the exoticgarden items as well as just a cs-corelib head every time

### ISSUE THREAD

**Issue by VideoConnected** [TheBusyBiscuit/ExoticGarden#169]
## Description (Required)
Upon breaking the exoticgarden heads they seem to just be cs-corelib heads I have absolutely no Idea on how to fix it the fact we use EWG doesn't make the stress on me any better I'm not able to just reset the world I've tried deleting the slimefun folder, exoticgarden, cs-corelib folder I went as far to delete the data-storage folder have it regenerate then upload the same one from before I'm desperate to find a solution to this I don't know if updating to the latest builds would work or if it'd break it even more every time a block is broken and returns a cs-corelib head an error pops up in console

## Steps to reproduce the Issue (Required)
Have absolutely No Idea on how to reproduce the issue except the fact it broke when another plugin was the cause of the server breaking entirely which was FactionsX where we had a slight issue with it

## Expected behavior (Required)
When I deleted the folders I expected them to regenerate and it start working again though that proved me clear wrong and this has happened on many other occasions as well I just never went out of my way to contact anyone just reset the worlds though now I am not able to do that as this is a fairly active factions server with 1 too many bases that I cannot just schem put back in etc as I've pre-genned the world that's another factor that plays into this
(Plugin I used to pre-gen would be)

- World-Border 1.16+

## Server Log / Error Report
https://pastebin.com/s0BbyE64 <Error from breaking a block and receiving the cs-corelib head

## Environment (Required)
https://imgur.com/a/SFYrslb <Shows all the versions listed

 - Minecraft Version: Paper 1.16.2-R2
 - CS-CoreLib Version: vDev 91
 - Slimefun Version: vDev 756
 - ExoticGarden Version: vDev 61

**Comment by TheBusyBiscuit** [comment]
That error is not coming from ExoticGarden, it's from your "Factions" plugin.
The Factions integration is handled by CS-CoreLib, so you should report it there instead:
https://github.com/TheBusyBiscuit/CS-CoreLib2

Also please include a **full** list of your plugins and the version and name of the Factions plugin you are using.

**Comment by VideoConnected** [comment]
> That error is not coming from ExoticGarden, it's from your "Factions" plugin.
> The Factions integration is handled by CS-CoreLib, so you should report it there instead:
> https://github.com/TheBusyBiscuit/CS-CoreLib2
> 
> Also please include a **full** list of your plugins and the version and name of the Factions plugin you are using.

I'm not able to create a new issue on the cs-corelib page for some odd reason

**Comment by TheBusyBiscuit** [comment]
Simply head to the repository, click the Issues tab and click on "New issue", then fill out the template.
https://github.com/TheBusyBiscuit/CS-CoreLib2/issues/new/choose

**Comment by VideoConnected** [comment]
> Simply head to the repository, click the Issues tab and click on "New issue", then fill out the template.
> https://github.com/TheBusyBiscuit/CS-CoreLib2/issues/new/choose

Totally my fault I got turned around on it and messed something up but I fixed it just now :)
