### ISSUE TITLE
Exception while generating terrain

### ISSUE THREAD

**Issue by bobhenl** [TheBusyBiscuit/ExoticGarden#170]
## Description (Required)

Hi, I have big spam at console today from some reason, don't know why this exactly happens, but it spams every second X times.
## Steps to reproduce the Issue (Required)

1. I probably unloaded world (using playerworlds plugin) and then this happened, but it happened for the first time.
2. Not sure, see error, may you will be clever.
## Expected behavior (Required)

Any NPE in console.
## Server Log / Error Report

https://pastebin.com/606MjuiM
## Environment (Required)

 - Minecraft Version: 1.16.4
 - CS-CoreLib Version: 91
 - Slimefun Version: 760
 - ExoticGarden Version: 61

**Comment by TheBusyBiscuit** [comment]
That's not an NPE... Why would you even say that?
