### ISSUE TITLE
Exotic Garden Error

### ISSUE THREAD

**Issue by RudeC** [TheBusyBiscuit/ExoticGarden#171]
## Description (Required)

It consist of error which is here:https://pastebin.com/3PxqjYZm
and this error is repeating but with other fruits or vegetables.

## Expected behavior (Required)

I would like if you could fix it because it is spamming my console so I can´t even read the console.

## Server Log / Error Report
https://pastebin.com/3PxqjYZm

## Environment (Required)
 - Minecraft Version: Yatopia v1_16_R3
 - CS-CoreLib Version: vDEV - 79 (git ec5b4c24)
 - Slimefun Version: vDEV - 765 (git 96c4d908)
 - ExoticGarden Version: vDEV - 62 (git 9cbd372e)

**Comment by WalshyDev** [comment]
There should be a schemas folder in the ExoticGarden folder. Delete that and the issue should be resolved. Please reply if it isn't.
