### ISSUE TITLE
Error With ExoticGarden and PlayerInteractEvent with Slimefun

### ISSUE THREAD

**Issue by JulianoAlpha123** [TheBusyBiscuit/ExoticGarden#172]
## Description (Required)
<!Hello, the slimefun plugin and addons are working normally, but there are several errors appearing on the console.

## Steps to reproduce the Issue (Required)
<!you don't have to do anything apparently

## Expected behavior (Required)

 - Minecraft Version: Spigot v1_14_R1
 - CS-CoreLib Version: CS-CoreLib vDEV - 79 (git ec5b4c24)
 - Slimefun Version: Slimefun vRC - 18 (git 3a9f9f04)
 - ExoticGarden Version: ExoticGarden vDEV - 62 (git 9cbd372e)

**Comment by TheBusyBiscuit** [comment]
Ehmm... are we supposed to guess what you are trying to report?

**Comment by JulianoAlpha123** [comment]
I'm sorry, I typed a lot of things but it doesn't seem like I'm going to
open a new one. I am sorry for the inconvenience.

Em seg, 7 de dez de 2020 15:43, TheBusyBiscuit <notifications@github.com>
escreveu:
