### ISSUE TITLE
Sweet Potato Pie was not registered in the Food Registry

### ISSUE THREAD

**Issue by Bettanation** [TheBusyBiscuit/ExoticGarden#176]
.register(plugin) is missing on line 445 in FoodRegistry.java causing sweet_potato_pie not to be registered therefore not showing.

**Comment by TheBusyBiscuit** [comment]
Please follow the template...

**Comment by SnowSnakz** [comment]
@TheBusyBiscuit does the template really matter that much? I mean there is very clearly enough information here...
