### ISSUE TITLE
Advanced farmer android will not chop exotic garden - magical plants today

### ISSUE THREAD

**Issue by oahawhool** [TheBusyBiscuit/ExoticGarden#185]
## Description (Required)

This morning advanced farmer droids were working perfectly, happily chopping the plants. This evening our server had a reboot.
Now, it WILL chop and replant netherwarts, but will not chop diamond or slime plants (the only ones i tested so far).

## Steps to reproduce the Issue (Required)

Use an advanced farmer with a magical plant.

## Expected behavior (Required)

Farmer should harvest and replant magical plants.

## Server Log / Error Report

I do not have access to server logs.

## Environment (Required)

![image](https://user-images.githubusercontent.com/58162831/106727513-2d72ca80-65d1-11eb-95bb-c083d0f19cf9.png)
I do not have access to the /sf versions command, therefore I am unable to determine which version we are running.

**Comment by oahawhool** [comment]
I went ahead and updated all the plugins on my own personal sf test server and had the same results, the current version is having this problem.

**Comment by oahawhool** [comment]
Boomer was kind enough to check, and was able to confirm.
![image](https://user-images.githubusercontent.com/58162831/106796332-ced53d00-6620-11eb-833b-a25d42b8340c.png)
Thank you so much!

**Comment by mav2020** [comment]
Just to add the Exotic Gardens version..., this bug occurs in Exotic Gardens version 71, but have not tested lower than that (I know it was not a problem in 61 with Slimefun 810).

**Comment by oahawhool** [comment]
Correct, it was not a problem until v71 (the latest). 
I checked with the server staff and my test server also run the latest v71. 
It is not possible for a player to get a server owner to roll back to a working version, so anyone that uses EG will be unable to use droids with Magical Plants until a newer fixed version is pushed. 
Hoping it will happen soon, because most of the people I play with are farmers.
Thank you so much for at least noticing this!

**Comment by oahawhool** [comment]
OK!  I tested by deleteing the coreCSLib to see if it's needed, and i rolled back to Dev86 version and the droids work perfectly, and do not need the corecslib.

**Comment by oahawhool** [comment]
Thank you very much for taking the time to stop what you were doing and fix this issue.
