### ISSUE TITLE
When you run it on the paper server (Kaze), all plants will no longer grow

### ISSUE THREAD

**Issue by 745404527** [TheBusyBiscuit/ExoticGarden#188]
## Description (Required)
When you run it on the paper server (Kaze), all plants will no longer grow.

Server Software ：Paper 
My Minecraft Version :1.16.2
CS-CoreLib Version:DEV-88
Slimefun Version:4.3-dev-200729

## Steps to reproduce the Issue (Required)
In this server environment, the plant will not grow and cannot be accelerated.

## Expected behavior (Required)
I thought it would grow.

## Server Log / Error Report
Sorry, I am not the administrator of this server.
I have no record of mistakes.

## Environment (Required)
Server Software ：Paper 
My Minecraft Version :1.16.2
CS-CoreLib Version:DEV-88
Slimefun Version:4.3-dev-200729
ExoticGarden：Latest version

**Comment by TheBusyBiscuit** [comment]
You are using an unofficial Slimefun version that was not made by us...
And "Latest version" is not a valid version...
