### ISSUE TITLE
My issue was "closed" but it didn't happen prior...

### ISSUE THREAD

**Issue by roracle** [TheBusyBiscuit/ExoticGarden#19]
In older versions of SF, I know for sure I could right-click a chest or an object with a berry and I'd retain the berry.  I know this because I try to keep a clean hotbar and an empty hand, and if a berry was ever in my hand I'd just keep up with right clicking, but it never removed the item beforehand.

Perhaps if there's a way to determine something along the following lines:
If the user right clicks on NOTHING then he can eat it.
If the user right clicks on SOMETHING then it should try to activate that something and not eat the berry.

**Comment by roracle** [comment]
Okay that's great, where's the 1.7 jar file?

**Comment by SoSeDiK** [comment]
It still needs some tests, so use at your own risk.
You can get a jar [here](https://www.dropbox.com/s/hortqgaoaw895x7/ExoticGarden%20v1.7.0.jar?dl=1) _(my DropBox)_ or compile it by yourself from sources.

**Comment by roracle** [comment]
I'm one of the few that I know who actively uses it, so let me know what needs testing and I'll get on it this week.

**Comment by SoSeDiK** [comment]
Everything needs testing :)
Just try it on a server with active players and let me know if they have found some bugs.
I'll be thankful.

**Comment by roracle** [comment]
Okay, right-clicking with an EG fruit head on EG bushes still consumes the EG fruit.  This does still need fixing, should I make a new "issue" with this, or  is this thread good enough?

**Comment by SoSeDiK** [comment]
That's good enough.
I'm not sure about beds. I included them into the "blacklist" for consuming.
I'll also add a rule for harvesting.
