### ISSUE TITLE
Exotic Garden Plants (Netherite/Diamond/Copper etc.) 

### ISSUE THREAD

**Issue by XxPoNaGeXx** [TheBusyBiscuit/ExoticGarden#190]
## Description (Required)
When planting a Copper Sappling it will grow to be a Copper Plant, that can be harvested into Copper Essence and later crafted to Copper.

##Actual Behaviour: 
Leaves decays if its not in touch with a type of Log, and will then leave the heads of the plant left and the sappling will no longer be collectable back. This breaks the plant and leaves the player with nothing

## Steps to reproduce the Issue (Required)
grow one

## Expected behaviour (Required)
When planting a Copper Sappling it will grow to be a Copper Plant

## Server Log / Error Report
N/A

**Comment by TheBusyBiscuit** [comment]
Missing versions.
Please follow our bug report template.
