### ISSUE TITLE
Dispenser can bypass disable-bonemeal setting

### ISSUE THREAD

**Issue by xMikux** [TheBusyBiscuit/ExoticGarden#193]
## Description (Required)
You can bypass when using Dispenser to grow.

## Steps to reproduce the Issue (Required)
https://youtu.be/3l73AIRT7xI
(Video will remove when it fix)

1. Go to Items.yml, enable plant disable-bonemeal true. (Here i use Netherite Plant)
2. Put it, and put dispenser in front of.
3. Put bone meal inside, using redstone signal to activate it.
4. And see it grow up.

## Expected behavior (Required)
Can't bypass

## Server Log / Error Report
No error.

## Environment (Required)

![image](https://user-images.githubusercontent.com/26039249/109656154-15c23e00-7b9f-11eb-88a1-fa0dc4f38604.png)

 - Minecraft Version: git-Paper-507 (MC: 1.16.5)
 - CS-CoreLib Version:
 - Slimefun Version: DEV - 825 (git 49950cf6)
 - ExoticGarden Version: vDEV - 74 (git 3366e8ac)

**Comment by WalshyDev** [comment]
This should no longer be an issue as of the latest Spigot and Paper builds. It may take some time for other forks to update.

**Comment by TheBusyBiscuit** [comment]
Fixed in the latest build of Spigot and Paper.
