### ISSUE TITLE
infinity bottles

### ISSUE THREAD

**Issue by RIPISDRAD** [TheBusyBiscuit/ExoticGarden#197]
hey there
1-you create 4 bottle of milk  with glass of bottle and 1 buckit of milk
2-you combine them with 4 coco beans
3-now you have 8 bottles of chocolate milk + 4 empty milk bottles
when you fill the emepty milk bottle with water and drink them it change the name to glass of bottle!
so at first u got 1 at the end u got 4

**Comment by TheBusyBiscuit** [comment]
Missing versions, template, etc...
