### ISSUE TITLE
 zinc and magnesium plants - Bug Report

### ISSUE THREAD

**Issue by AccioAce** [TheBusyBiscuit/ExoticGarden#198]
## Description (Required)
It seems like zinc and magnesium plants are not in the sf guide or the items.yml file as I checked.

## Steps to reproduce the Issue (Required)
I explained above.

## Expected behavior (Required)
I was expecting zinc and magnesium plants to be added in the sf guide and items.yml. 

## Server Log / Error Report
I do not have any error reports or logs. 

## Environment (Required)

ExoticGarden - DEV 75 (git 6c3e5) - Screenshot: https://gyazo.com/294ea30f50ef12f9b54c6eb23aa22725?token=eea0b26521e934808dab69d28d0d9e4f

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: CS-CoreLib was no longer required
 - Slimefun Version: RC - 21 (git c1fb5e12)
 - ExoticGarden Version: ExoticGarden - DEV 75 (git 6c3e5)

**Comment by TheBusyBiscuit** [comment]
1. We do not support RC versions
2. There is no Zinc or Magnesium Plant.
3. Suggestions go on discord.
