### ISSUE TITLE
Plants can still be bonemeal using dispenser

### ISSUE THREAD

**Issue by Skizzles** [TheBusyBiscuit/ExoticGarden#200]
## Description (Required)

Bonemeal being disabled can be bypassed by dispenser

## Steps to reproduce the Issue (Required)

https://screenshots.skizzles.me/wAnA3/CUyOjusu06.mp4

## Expected behavior (Required)

Have it blocked

## Server Log / Error Report

No Errors

## Environment (Required)

https://screenshots.skizzles.me/wAnA3/KiWeZEbO09.png

**Comment by TheBusyBiscuit** [comment]
Duplicate of #193
