### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by JustinDevB** [TheBusyBiscuit/ExoticGarden#202]
## Description (Required)

Console error when breaking grass for seeds
## Steps to reproduce the Issue (Required)

Break grass
## Expected behavior (Required)

No error to be thrown.

## Server Log / Error Report

https://pastebin.com/RYDajMUa
## Environment (Required)

![2021-04-21_17 32 28](https://user-images.githubusercontent.com/6395878/115623741-95c77300-a2c7-11eb-8b0b-158ac435d142.png)
 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - ExoticGarden Version:

**Comment by WalshyDev** [comment]
Do you have 2 ExoticGarden jars. It looks like it.
