### ISSUE TITLE
麻烦更新 1.17.1

### ISSUE THREAD

**Issue by bzhaoqi** [TheBusyBiscuit/ExoticGarden#221]
## Environment (Required)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - ExoticGarden Version:

**Comment by MagmaBro123** [comment]
Not giving info is gonna get this closed.

**Comment by ybw0014** [comment]
First, English please.
This plugin is compatible with 1.17.1.
