### ISSUE TITLE
Missing Zinc and Magnesium Plants (ExoticGardens)

### ISSUE THREAD

**Issue by Kyuri-Oji** [TheBusyBiscuit/ExoticGarden#226]
## Description (Required)
All the types of magical plants are present in the plugin apart from the Zinc and Magnesium Plants.
Could we please have this added? The last person submitted a report as far back as 5 April 2020.

## Steps to reproduce the Issue (Required)
/sf open_guide, it's just not there.

## Expected behavior (Required)
For there to be Zinc and Magnesium Plants added.

## Server Log / Error Report
No error report, just missing items from the slimefun roster.

## Environment (Required)
I've included an image of my /sf versions.

![image](https://user-images.githubusercontent.com/67164260/150640084-8b3d4dc7-031f-4b60-881d-8e75de38222e.png)

**Comment by TheBusyBiscuit** [comment]
This doesn't look like a bug report, it sounds more like a feature request.
Please post your suggestions on discord and not on our bug tracker.
