### ISSUE TITLE
Fruits dropping from trees

### ISSUE THREAD

**Issue by jordanwilliams1** [TheBusyBiscuit/ExoticGarden#23]
When you're mining a tree with fruits on it you're getting way more fruits than you should. There is like 10 fruits on a tree but you're getting like 30 plus. It would be nice if you just reverted the change. It's become a problem on our server so we've had to downgrade the plugin but a lot of things aren't working due to this :/

**Comment by TheBusyBiscuit** [comment]
Dont spam
