### ISSUE TITLE
CSCoreLib's Head Drops Instead of Fruit Textures

### ISSUE THREAD

**Issue by Coolkc456** [TheBusyBiscuit/ExoticGarden#26]
Describe your Issue AS DETAILED AS POSSIBLE.
Everytime someone breaks a Slimefun Exotic Harden head, CSCoreLib's head drops. I tried regenerated the entire Slimefun files yet the problem persists. I'm also unable to right-click bushes and get fruits. The bushes do not break upon right-clicking and simply just appear as leaves.

Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.
https://pastebin.com/iLJUSWUc

Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.
https://www.youtube.com/watch?v=WvvTjJVncpU&feature=youtu.be

Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.
Craftbukkit v1_12_R1
CS-CoreLib v1.5.16
Slimefun v4.1.13
ExoticGarden v1.6.3

**Comment by Meta-Win** [comment]
Bad English***

It's happens too with a new world? Maybe you have deleted the slimefun data folder.
