### ISSUE TITLE
1.13 Support

### ISSUE THREAD

**Issue by jordanwilliams1** [TheBusyBiscuit/ExoticGarden#32]
The plugin doesn't have 1.13 support, The trees don't grow on 1.13. This is by far the best plugin I've seen on Minecraft. It adds a whole new farming aspect to the game. 

I Really hope you update it to 1.13, If not today, maybe in the future. I'd love to keep this. I First time i saw this I was amazed.

**Comment by TheBusyBiscuit** [comment]
I quit development on plugins years ago, its up to the community to make a pull request for an update.

**Comment by jordanwilliams1** [comment]
Alright thanks for the update @TheBusyBiscuit
