### ISSUE TITLE
The new build is null

### ISSUE THREAD

**Issue by MineCraftael** [TheBusyBiscuit/ExoticGarden#33]
Where are all the recipes? And the craft do not want to be displayed! In addition I can not have a seed in the high grass!

Can someone correct all his?
Thank you

(PS: sorry for my english :p)

**Comment by MineCraftael** [comment]
Why did you close?

**Comment by TheBusyBiscuit** [comment]
Your issue does not contain any useful information at all.
MC Version?
Bukkit Version?
CS-CoreLib Version?
Slimefun Version?
ExoticGarden Version?
Server Log?
Error Report?
Crash Report?
Any messages in the console?
Did you check that you are using the latest versions of all your plugins?
Did you check that your versions are compatible with the MC/Slimefun Version you are using?
Screenshots?

You did not provide any of that, so we cannot provide you any help either.
