### ISSUE TITLE
Any intention to update to 1.13?

### ISSUE THREAD

**Issue by DrakstaarMSD** [TheBusyBiscuit/ExoticGarden#36]
Is there any intention to update to 1.13?
I have made an attempt myself.
Swapping in the new item IDs was pretty straight forward.
However, i am no coder and have only had limited success.
The tree code has me a bit confused. Also I can't seem to figure out how to rebuild the tree schematics in 1.13 properly. 
I have managed to get the other plants to grow without errors.

**Comment by xH3LLRAIZ3Rx** [comment]
Yeah, I am having the same issue trying to fix the schematic class

**Comment by DrakstaarMSD** [comment]
I can't even get it to spawn anything other than a normal oak tree. 
I get and error that it can't pass StructureGrowEvent to Exoticgardens

**Comment by DrEthan77** [comment]
so how is this coming to fix?

**Comment by DrEthan77** [comment]
i think it is because of how this is using schematics and that is no longer supported in 1.13
