### ISSUE TITLE
Magial plants doesn't works

### ISSUE THREAD

**Issue by hunterdu42** [TheBusyBiscuit/ExoticGarden#38]
Hello,

I would like to translate the exotic garden plugin. But when i export the project in jar file with eclipse sofware to make it on my minecraft server, all items appears in the slimefun guid but not the section "magical plant" (ore plant) (confers image).

http://image.noelshack.com/fichiers/2018/42/6/1539986791-error-exotic-garden.png

The magical plants works with the plugin available on bukkit but no with all versions presents on github. Homewer, the magical plants code is present in the code of the github. Did a make a bad manipulation ? Have I forgotten a step ?

I searched everywhere but no solution :/.

Can you help me ? 

I Thank you in advance !

Best regards

**Comment by Yang161941** [comment]
maybe here is no solution at present
see #16
