### ISSUE TITLE
Sapling for trees/bushes all grow as oak trees -- errors in console (1.13)

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/ExoticGarden#42]
versions
CraftBukkit v1_13_R2
CS-CoreLib vDEV - 33 (git e509a156)
Slimefun vDEV - 65 (git 81dc3e4a)
ExoticGarden vDEV - 3 (git 8e3785ee)

Try planting any Exotic Garden sapling and observe results to duplicate... also when loading chunks (after random teleport, for example, changing worlds... etc,) or after just standing around for any length of time anywhere:
(primarily a flood of "Could not pass event ChunkPopulateEvent to ExoticGarden vDEV - 3 (git 8e3785ee)"):
https://pastebin.com/QFLwWEzZ

**Comment by TheBusyBiscuit** [comment]
ExoticGarden is not built for 1.13, it still lives on 1.12, that is why you are getting these errors.
