### ISSUE TITLE
1.13.2 Issues (For The New Update)

### ISSUE THREAD

**Issue by DJTheAlphaWolfz** [TheBusyBiscuit/ExoticGarden#43]
With the 1.13.2 update you've just worked on, there are two main functions missing or resulting in an error.

1: I'm assuming (with the help of problem two) that you can actually make the food in the Kitchen. When finding a wild plant and right clicking it, it does drop the item. It also continues to grow and supply you with the corresponding fruit or vegetable. Although, when breaking the plant and moving it to a different location, the NBT tag does not save and it just grows into a normal oak tree.

2: The Kitchen recipe does not appear in the GUI menu when left clicking on its cauldron. I've tried going through the source code, but I'm no developer. I cannot figure out the solution myself nor do I know the MultiCraft recipe for the machine in order to make any sort of ExoticGarden food.

I hope you take these issues into consideration. Have a wonderful day!

**Comment by TheBusyBiscuit** [comment]
There is no 1.13.2 Update, ExoticGarden is still for 1.12
