### ISSUE TITLE
Kitchen non functional.

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/ExoticGarden#46]
CraftBukkit v1_12_R2

CS-CoreLib vv1.5.18
Slimefun vDEV 4-52
ExoticGarden vDev - 3

Since mrcookieslime has made it clear this is NOT for 1.13.2, I'd still like it to work for 1.12.2 even though we'll need some sort of codex for determining what version works with what these days.  This is the combination I've got on my server now which results in the kitchen either eating the ingredients and producing no resulting product, or saying "Sorry, my Inventory is too full!"  in spite of the fact only the top row of the dispenser is in use... and so it will not craft any of the exotic garden recipes.  If this is designed to work with a different version of CS-Core and/or Slimefun, please advise the versions as I've tested every CS-Core version back to CS-Corelib-28... this is the first version that doesn't result in an error under 1.12.2.  Slimefun-Dev 4-52 is the last version that doesn't say "this is the wrong version of minecraft", so presumably, you must be using this version.  Please expedite, thanks!

**Comment by SoSeDiK** [comment]
I can't reproduce your issue with provided versions of CS-CoreLib, Slimefun and ExoticGarden. I only disabled auto-update, everything else has default settings. Can you provide some more information?
Like what recipes were used, how many times etc? Or just a video would be great.
Note: You should put proper items in the dispenser and the result will be in a furnace.

**Comment by mrcoffee1026** [comment]
making this the only SF machine that uses a block of the build NOT the dispenser as output.   Yes, that's what's happening... the result is in the furnace.  The "sorry my inventory is too full" is what happens when you have no idea the items are being stashed in there and so don't remove them.
