### ISSUE TITLE
Can you make the download available?

### ISSUE THREAD

**Issue by DJTheAlphaWolfz** [TheBusyBiscuit/ExoticGarden#47]
So, I see the 1.13.2 update pull request has been merged... But how do you download the actual jar file? ._. Yes, I have everything properly updated. Both Slimefun and CS-Corelib, but Exotic Garden's latest update doesn't appear to be here... https://thebusybiscuit.github.io/builds/ Can you add it so people can download the 1.13.2 build?

**Comment by TheBusyBiscuit** [comment]
It happens automatically.
But the system is currently broken and it takes a while to fix.
The project is not compiling at the current state anyway.
