### ISSUE TITLE
Chocolate bar recipe uses an Ink sac instead of cocoa beans.

### ISSUE THREAD

**Issue by EnderSlime123** [TheBusyBiscuit/ExoticGarden#52]
I'm using the latest version of Slimefun and CS-CoreLib for MC 1.13.2, as well as the latest Paper build.

Sorry if this isn't enough info.

**Comment by TheBusyBiscuit** [comment]
Fixed in #49

A compiled update can be found here:
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/ExoticGarden/master/
