### ISSUE TITLE
ExoticGarden Can't eat Cheese

### ISSUE THREAD

**Issue by Spuito65** [TheBusyBiscuit/ExoticGarden#53]
A mob dropped cheese and im not able to eat it, and i gathered coconuts from a tree it said Core Libs Head and cannot be eaten too.

**Comment by SoSeDiK** [comment]
Cheese is not related to ExoticGarden, it is Slimefun item.
CS-CoreLib heads issue is already known and reported in Slimefun repository, and has nothing to do with ExoticGarden as well *(because Slimefun handles saving player heads by itself)*.
