### ISSUE TITLE
Kitchen structure not being detected.

### ISSUE THREAD

**Issue by EnderSlime123** [TheBusyBiscuit/ExoticGarden#56]
Using latest version of everything.

**Comment by SoSeDiK** [comment]
@EnderSlime123, can you try with the new build?

**Comment by EnderSlime123** [comment]
> @EnderSlime123, can you try with the new build?

I'm using the latest build.

https://thebusybiscuit.github.io/builds/TheBusyBiscuit/ExoticGarden/master/#7

**Comment by SoSeDiK** [comment]
Well, it works for me.
Are you using it corectly?
The result goes to the furnace and the "starting" block is the iron trapdoor.

**Comment by EnderSlime123** [comment]
> Well, it works for me.
> Are you using it corectly?
> The result goes to the furnace and the "starting" block is the iron trapdoor.

I am.

**Comment by SoSeDiK** [comment]
Switch the trapdor and the stone plate xD

**Comment by EnderSlime123** [comment]
> Switch the trapdor and the stone plate xD

Figured it out.
