### ISSUE TITLE
[minor] Amusing issue with coconut tree generation on 1.13

### ISSUE THREAD

**Issue by AeSix** [TheBusyBiscuit/ExoticGarden#57]
https://puu.sh/D76AC/3bea37901c.png

There has been generated a coconut tree (will coconuts) in a "deep_lukewarm_ocean" biome. 

It seems not to be causing any problems, but may need to be looked at. 

ExoticGarden Dev 7
CS-CoreLib Dev 36
SlimeFun4 Dev 82

**Comment by SoSeDiK** [comment]
Woah! It looks so wrong!
I suppose it's because of 1.13 vegetation in ocean biomes.
I'll into this.

**Comment by AeSix** [comment]
@SoSeDiK 
This is less worrisome than the coconut palm... 
But I just found a dragon fruit tree in "snowy_mountains" 

I don't know if there's at all a biome consideration when generating trees... but this is just a little weird.  

https://puu.sh/D799p/cc9e138f74.png

I didn't bother opening a new ticket because I don't believe it's an actual issue.  Sorry to be annoying if I am >_>

**Comment by AeSix** [comment]
OK.  Sorry for the spam. 
I just found a lot of naturally generated rails at top side of the world.  I'm begining to think the SF trees spawning may be affected by the use of Multiverse-Core... and may be the reason we have mine tracks on the surface. 

I could be wrong on that and just being overly sensitive.  But worth a note.  :)

**Comment by SoSeDiK** [comment]
It is not a bug, it always was like that. Snow is not a solid block and it has a grass block under it, so tree can grow there.
I can deny spawning in some biomes (maybe a list in config?) if you want. Although you still can plant a tree there and it will grow up.

**Comment by AeSix** [comment]
No, I just thought there were biome-centric plants. 
That would be a cool feature, but probably a lot of work to implement. 

Thank you for explanation! :D 🎉
