### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by lukemango** [TheBusyBiscuit/ExoticGarden#62]
I'm not sure what's causing this:
https://pastebin.com/LZH8Q6LU

**Comment by lukemango** [comment]
https://pastebin.com/BfPLg60s

**Comment by STEngineer** [comment]
Use this build for 1.13: https://thebusybiscuit.github.io/builds/TheBusyBiscuit/ExoticGarden/master/ExoticGarden-8.jar
