### ISSUE TITLE
Heads turn into CSCore-Lib heads.

### ISSUE THREAD

**Issue by EnderBro123** [TheBusyBiscuit/ExoticGarden#67]
**Currently using this on a friends server.**

ExoticGarden heads (All of them) turn into CSCoreLib's Heads upon trying to use them/place them.

![2019-06-12_17 19 31](https://user-images.githubusercontent.com/51277766/59394902-55475780-8d36-11e9-95b0-41eeb774355e.png)

No console errors appear.

**Comment by BluGhostYT** [comment]
Delete your data-storage folder. That seems to be the cause of it most of the time.
