### ISSUE TITLE
Issue when using McMMO's Tree Feller on the trees

### ISSUE THREAD

**Issue by Hellcode48** [TheBusyBiscuit/ExoticGarden#7]
When using McMMO's Tree Feller on any trees dupes the amount of fruit dropped from latest change to the plugin where the fruit decays.

**Comment by Volander** [comment]
Is this not "working as intended"? You also get doubledrops from using superbreaker on minerals?

**Comment by roracle** [comment]
Since mcMMO has never resolved their special abilities issues, I just disable them all.  No one should be using them if others are connecting unless you just love ghost blocks. :P

**Comment by MsArtix** [comment]
Edit to this issue is that when using MCMMO treefeller it also glitches out the fruit blocks and you cannot place/break the block where the fruit was/is.
