### ISSUE TITLE
Build 15 of ExoticGarden wont load at all

### ISSUE THREAD

**Issue by EnderBro123** [TheBusyBiscuit/ExoticGarden#76]
## Description (Required)

Upon trying to use the latest build of ExoticGarden (Build #15 (Ignore the hyperlink, lol.)), it doesn't load.

## Steps to reproduce the Issue (Required)

Put the new build of ExoticGarden in your plugins folder, then restart your server. If you type /plugins or /pl, it isn't showing it.

## Expected behavior (Required)

The plugin loads normally.

## Server Log / Error Report

No errors appear.

## Environment (Required)

![2019-06-27_11 39 42](https://user-images.githubusercontent.com/51277766/60291697-47660a80-98d0-11e9-961d-3c5314a02d62.png)

**Comment by BluGhostYT** [comment]
ExoticGarden is 1.14.2, not 1.13....

**Comment by SoSeDiK** [comment]
Oh, didn't know we still support 1.13.
Try changing 'api-version: 1.14' to 'api-version: 1.13' in plugin.yml and respond here if it works or not.

**Comment by BluGhostYT** [comment]
You'll have to recompile it

**Comment by EnderBro123** [comment]
> You'll have to recompile it

How can I do this?

**Comment by BluGhostYT** [comment]
> > You'll have to recompile it
> 
> How can I do this?

Download the source code, extract it, go into the folder, find plugin.yml, open it and edit the api-version part, then, save the yml, open a CMD prompt in that folder, and type mvn clean package. You have to have Maven in order to do this.

**Comment by TheBusyBiscuit** [comment]
@BluGhostYT You know, someone could also just change the api-version tag here on github...

**Comment by EnderBro123** [comment]
> > > You'll have to recompile it
> > 
> > 
> > How can I do this?
> 
> Download the source code, extract it, go into the folder, find plugin.yml, open it and edit the api-version part, then, save the yml, open a CMD prompt in that folder, and type mvn clean package. You have to have Maven in order to do this.

This Maven? https://maven.apache.org/

**Comment by BluGhostYT** [comment]
> > > > You'll have to recompile it
> > > 
> > > 
> > > How can I do this?
> > 
> > 
> > Download the source code, extract it, go into the folder, find plugin.yml, open it and edit the api-version part, then, save the yml, open a CMD prompt in that folder, and type mvn clean package. You have to have Maven in order to do this.
> 
> This Maven? https://maven.apache.org/

Yes

**Comment by BluGhostYT** [comment]
Opened a PR for the changing of the API version. Please wait until the issue is closed :>

**Comment by EnderBro123** [comment]
> > > > > You'll have to recompile it
> > > > 
> > > > 
> > > > How can I do this?
> > > 
> > > 
> > > Download the source code, extract it, go into the folder, find plugin.yml, open it and edit the api-version part, then, save the yml, open a CMD prompt in that folder, and type mvn clean package. You have to have Maven in order to do this.
> > 
> > 
> > This Maven? https://maven.apache.org/
> 
> Yes

![image](https://user-images.githubusercontent.com/51277766/60292546-39b18480-98d2-11e9-925c-6beea3ee7854.png)

**Comment by TheBusyBiscuit** [comment]
@BluGhostYT Why should I wait...?

**Comment by BluGhostYT** [comment]
> @BluGhostYT Why should I wait...?

That was towards Ender

**Comment by BluGhostYT** [comment]
> > > > > > You'll have to recompile it
> > > > > 
> > > > > 
> > > > > How can I do this?
> > > > 
> > > > 
> > > > Download the source code, extract it, go into the folder, find plugin.yml, open it and edit the api-version part, then, save the yml, open a CMD prompt in that folder, and type mvn clean package. You have to have Maven in order to do this.
> > > 
> > > 
> > > This Maven? https://maven.apache.org/
> > 
> > 
> > Yes
> 
> ![image](https://user-images.githubusercontent.com/51277766/60292546-39b18480-98d2-11e9-925c-6beea3ee7854.png)
> 
> Look, I never use "Tar" or "Gz" files so I'm confused.

Download the zip.

**Comment by EnderBro123** [comment]
> @BluGhostYT Why should I wait...?

Anyways, can we atleast still support 1.13/1.14?
