### ISSUE TITLE
Exotic Garden + Epic World Generator = Does not work

### ISSUE THREAD

**Issue by EmanuelSimard** [TheBusyBiscuit/ExoticGarden#79]
## Description (Required)
Slimefun Exotic Garden trees are growing into big trees (From the famous plugin Epic World Generator). Is there a way to stop this from happening?

## Steps to reproduce the Issue (Required)
Place a sapling from Exotic Garden on the grass/dirt until it grows into a tree

I was expecting that the exotic garden trees would grow rather than an enormous tree.

 - Minecraft Version: 1.13.2
 - CS-CoreLib Version: 1.6.1
 - Slimefun Version: vDev - 58 (git 18881806)
 - ExoticGarden Version: 1.6.3

**Comment by TheBusyBiscuit** [comment]
That is something the author of EpicWorldGenerator has to fix then, nothing that can be done about it from here.
