### ISSUE TITLE
Schematics class outdated, need to update to sponge type

### ISSUE THREAD

**Issue by xH3LLRAIZ3Rx** [TheBusyBiscuit/ExoticGarden#86]
## Description (Required)
Any new trees cannot be added to Exotic Garden because the schematics class is outdated.
Someone needs to recode the schematics class to fit the new Sponge schematic type, mcedit is obsolete.

## Steps to reproduce the Issue (Required)
Create tree schematic
schematic is saved as a schem file now because worldedit changed the schematic saving structure.
Doesn't work in the long run because the class is outdated

## Expected behavior (Required)
I expected it to fail which it did.

## Environment (Required)

 - Minecraft Version: 1.14.4
 - CS-CoreLib Version: vDev 69
 - Slimefun Version: vDev 247
 - ExoticGarden Version: Dev 18

**Comment by TheBusyBiscuit** [comment]
Schematics aren't handled by ExoticGarden.
ExoticGarden just uses the public JNBT API for Schematics, so this issue does not belong here, the implementation should just be swapped out if one is available.
