### ISSUE TITLE
Plants not growing as Intended

### ISSUE THREAD

**Issue by K1llersaur** [TheBusyBiscuit/ExoticGarden#91]
## Description (Required)
Exotic garden trees growing into oak trees on my server

## Steps to reproduce the Issue (Required)
Plant tree, wait or bonemeal it, tree turns into an oak tree. Occurs with other plants too

## Expected behavior (Required)
I have been on a server with this addon and normally it will turn into the right plant

## Server Log / Error Report
https://pastebin.com/nif8TvkT As said there I am pretty sure it is related to the message near the top. I still don't know how to resolve this though

## Environment (Required)

 - Minecraft Version:
 - CS-CoreLib Version:  CS-CoreLib%20v1.6.1.jar and CS-CoreLib%2Bv1.6.1.jar 
 - Slimefun Version:  Slimefun4 - RC 2 (git 4bb9a).jar (?)
 - ExoticGarden Version: ExoticGarden v1.6.3

(there are two CS Corelibs idk why I am gonna try to remove one in a bit but last time I did some weird things happened so I just haven't touched it yet)

**Comment by K1llersaur** [comment]
You could have just said why but okay guess I am just not gonna get help anywhere

**Comment by TheBusyBiscuit** [comment]
Since I haven't made a script for this repo yet, there you go:

https://github.com/TheBusyBiscuit/Slimefun4/issues/1252#issuecomment-555251922

**Comment by Burgersim** [comment]
May I ask, because I have the same Problem, and don't really get it, has this been resolved actually? I tried updating to the newest CSCoreLib, but that didn't fix it

**Comment by J3fftw1** [comment]
@Burgersim update slimefun might alsk be fixed in stable 3

**Comment by threlief** [comment]
i also have this issue ??
