### ISSUE TITLE
Plants don't stack sometimes

### ISSUE THREAD

**Issue by Burgersim** [TheBusyBiscuit/ExoticGarden#93]
## Description (Required)
I was just trying out harvesting a lot of Plants and Seeds by breaking Grass when I realized that (seemingly randomly) some of them don't stack. 

I thought I'd provide some Screenshots including the NBT Data I got using a mod to display NBT Data:
![2019-12-02_16 15 36](https://user-images.githubusercontent.com/26793150/69971039-966b3800-151f-11ea-8a79-30418d437f75.png)
![2019-12-02_16 15 41](https://user-images.githubusercontent.com/26793150/69971041-9703ce80-151f-11ea-8580-e4e80ef11795.png)
![2019-12-02_16 16 00](https://user-images.githubusercontent.com/26793150/69971042-979c6500-151f-11ea-9a97-05099a63ff44.png)
![2019-12-02_16 16 05](https://user-images.githubusercontent.com/26793150/69971045-979c6500-151f-11ea-92eb-76fd6c6a8352.png)
![2019-12-02_16 16 12](https://user-images.githubusercontent.com/26793150/69971048-98cd9200-151f-11ea-9830-17c4e0cba971.png)
![2019-12-02_16 16 16](https://user-images.githubusercontent.com/26793150/69971050-99662880-151f-11ea-8bf8-cc4d72a8a920.png)

## Steps to reproduce the Issue (Required)
Just gather up some Plants randomly by breaking tall grass.

## Expected behavior (Required)
The Same Plants should stack to the same Inventory Spot.

## Server Log / Error Report
I do not have a Server log right now, but If you tell me what you need me to do I can provide a log, I just don't think you wont see a lot now, while I was only making the Screenshots.

## Environment (Required)
I'm using

Minecraft Version 1.14.4
CS-CoreLib - DEV 78 (git 199e1).jar
ExoticGarden - DEV 22 (git a855f).jar
Slimefun4 - DEV 339 (git 28ed7).jar

**Comment by Burgersim** [comment]
Well, did I do sthg wrong? Or is this known already? Is there a way to fix it?

**Comment by TheBusyBiscuit** [comment]
This is not a bug...
Some of them just have NBT data, some do not.

ExoticGarden is very old and causes a lot of problems, it still uses an old item system.

I think left or right clicking should convert them.

**Comment by Burgersim** [comment]
Ok thx, I'll try that
