### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Yukyxy** [TheBusyBiscuit/ExoticGarden#95]
Hello, 
suggestion: Could you add please in the config file the possibility to define the sapling drop rate for all trees and plants. It will be great if you could do that because plants and trees drop very often saplings and too much which do the gameplay really too easy and fast (without too much challenge). Thanks in advance for your answer.

**Comment by TheBusyBiscuit** [comment]
This is not a Bug Report...
Suggestions aren't allowed here, you may ask someone on Slimefuns discord or so.
