### ISSUE TITLE
Build #23 doesn't work

### ISSUE THREAD

**Issue by jordanwilliams1** [TheBusyBiscuit/ExoticGarden#97]
Build #23 doesn't work :( 
https://i.gyazo.com/90a4ed35a9922145496f777e7ff30413.png

Build #22 dose however work fine but it auto-updates to #23

**Comment by SoSeDiK** [comment]
Make sure you are using the latest builds of Slimefun and CS-CoreLib too.

**Comment by jordanwilliams1** [comment]
@SoSeDiK Oh i see.. It works. I only updated them a few day ago. Do you think it would be possible to disable the auto update on this plugin please?

**Comment by SoSeDiK** [comment]
Yes, there should be an option in the config file.
