### ISSUE TITLE
Plants invisible: can't place there [VIDEO]

### ISSUE THREAD

**Issue by itslukemango** [TheBusyBiscuit/ExoticGarden#98]
## Steps to reproduce the Issue (Required)

https://streamable.com/givfz
Planted cherry plants, bonemeal it a good amount and then lumberaxe it. All of them broke.

## Expected behavior (Required)

The plant to actually drop and the block be placeable

## Server Log / Error Report

Not necessary for this issue; if you need it please DM me.

## Environment (Required)

 - Minecraft Version: 1.14.4 Paper 237
 - CS-CoreLib Version: DEV 79
 - Slimefun Version: DEV 384
 - ExoticGarden Version: DEV 23

**Comment by SoSeDiK** [comment]
I think it's more likely a Slimefun issue?
1. The original sapling wasn't removed through `BlockStorage.clearBlockInfo(e.getLocation());`
2. I believe there's a WorldEdit hook in Slimefun, which should remove data from storage when manipulating with blocks. Still, ExoticGarden's saplings were not removed.
3. So there's a placed block now, and you can break it. It drops a proper SF (EG) item but doesn't get removed from the storage at this point as well.

Those three parts should be handled by Slimefun.
Anyway, is this still an issue? Are there any errors or something? I can't reproduce that, and I have no clue what's going wrong here.
